profiles:
  - profile: Desktop Views
    view_mode: tab
    tabs:
      - name: projects
        url: https://www.phipluspi.com/project/
        width: 1440
      - name: goove
        url: https://www.goove.at/
        width: 1440

  - profile: Mobile Views
    view_mode: tab
    tabs:
      - name: projects
        url: https://www.phipluspi.com/project/
        width: 768
      - name: goove
        url: https://www.goove.at/
        width: 768